cluster_file: '/Users/sweveret/repos/palomar-proposal-2022S/data/redmapper_dr8_public_v6.3_catalog_airmass.fits'
source_file: '/Users/sweveret/repos/palomar-proposal-2022S/data/portsmouth_emlinekin-DR12.fits'
# matched_file: '/Users/sweveret/repos/palomar-proposal-2022S/data/10arcmin-match.fits'

cluster_outfile = '/Users/sweveret/repos/palomar-proposal-2022S/data/added_cols_redmapper_dr8_public_v6.3_catalog.fits'
source_outfile = '/Users/sweveret/repos/palomar-proposal-2022S/data/added_cols_portsmouth_emlinekin-DR12.fits'
match_outfile = '/Users/sweveret/repos/palomar-proposal-2022S/data/palomar_matched_catalog.fits'

plot: True
overwrite: False

# will want to skip airmass if already run (very slow)
run: ['cluster_preprocess', 'source_preprocess', 'match', 'shear']

airmass:
  start_date: '2022-08-01'
  end_date: '2023-01-31'
  utc_offset: -7
  min_airmass: 1.3

match:
  radius: 5./60. # deg

shear:
  min_g: 0.0
  max_g: 0.2

visible:
  blue_lim: 330 # nm
  red_lim: 770 # nm
  lines:
    'halpha': 656.3 # nm
    'O2': 373 # nm



